"""
Wald contrast computations for motif effects.

This module provides functions for constructing and testing linear contrasts
of model coefficients. These are used to compare motif effects between
different phenotypes.

Functions
---------
coef_name_for_motif_phenotype
    Generate the coefficient name for a motif-phenotype interaction.
motif_diff_between_phenotypes
    Build a contrast vector for comparing motif effects between phenotypes.
wald_contrast
    Perform a Wald test on a linear contrast.
"""
from __future__ import annotations

from typing import Tuple

import numpy as np


def coef_name_for_motif_phenotype(motif: str, phenotype: str) -> str:
    """Generate the coefficient name for a motif-phenotype interaction.

    Constructs the coefficient name as generated by patsy when using
    treatment coding without an intercept (``0 + C(phenotype)``).

    Parameters
    ----------
    motif : str
        Name of the motif feature (e.g., "ELM_SH3").
    phenotype : str
        Name of the phenotype level (e.g., "EM_High").

    Returns
    -------
    str
        Coefficient name in patsy format: "motif:C(phenotype)[phenotype]"

    Examples
    --------
    >>> coef_name_for_motif_phenotype("ELM_SH3", "EM_High")
    'ELM_SH3:C(phenotype)[EM_High]'
    """
    return f"{motif}:C(phenotype)[{phenotype}]"


def motif_diff_between_phenotypes(
    fit, motif: str, p: str, q: str
) -> Tuple[np.ndarray, str]:
    """Build a contrast vector for comparing motif effects between phenotypes.

    Constructs a linear contrast vector L such that L @ beta gives the
    difference in the motif's effect between phenotype p and phenotype q:
    beta_{motif:p} - beta_{motif:q}

    Parameters
    ----------
    fit : FitResult
        Fitted model result from :func:`fit_nb_glm_iter_alpha`.
    motif : str
        Name of the motif feature.
    p : str
        First phenotype (the "numerator" in the comparison).
    q : str
        Second phenotype (the "denominator" in the comparison).

    Returns
    -------
    L : np.ndarray
        Contrast vector of shape (1, n_coefficients).
    name : str
        Descriptive name for the contrast.

    Raises
    ------
    KeyError
        If the required coefficients are not found in the model.

    Examples
    --------
    >>> L, name = motif_diff_between_phenotypes(fit, "ELM_SH3", "EM_High", "CM_High")
    >>> print(name)
    ELM_SH3: EM_High - CM_High
    """
    cols = fit.data_cols
    L = np.zeros((1, len(cols)))

    cn_p = coef_name_for_motif_phenotype(motif, p)
    cn_q = coef_name_for_motif_phenotype(motif, q)

    if cn_p not in cols or cn_q not in cols:
        missing = [c for c in (cn_p, cn_q) if c not in cols]
        raise KeyError(f"Missing coefficients: {missing}")

    L[0, cols.index(cn_p)] = 1.0
    L[0, cols.index(cn_q)] = -1.0
    name = f"{motif}: {p} - {q}"
    return L, name


def wald_contrast(
    fit,
    L: np.ndarray,
    name: str,
) -> Tuple[float, float]:
    """Perform a Wald test on a linear contrast.

    Computes the estimate and p-value for a linear combination of
    coefficients using the Wald test statistic.

    Parameters
    ----------
    fit : FitResult
        Fitted model result from :func:`fit_nb_glm_iter_alpha`.
    L : np.ndarray
        Contrast vector of shape (1, n_coefficients).
    name : str
        Descriptive name for the contrast (for error messages).

    Returns
    -------
    estimate : float
        The estimated value of L @ beta (on the log scale).
    pvalue : float
        Two-sided p-value from the Wald test.

    Examples
    --------
    >>> L, name = motif_diff_between_phenotypes(fit, "ELM_SH3", "EM_High", "CM_High")
    >>> est, pval = wald_contrast(fit, L, name)
    >>> print(f"Effect: {est:.3f}, p-value: {pval:.3e}")
    Effect: 0.523, p-value: 1.234e-05
    """
    test = fit.res.t_test(L)
    # Handle both scalar and array results
    effect = test.effect
    pvalue = test.pvalue
    est = float(effect.item()) if hasattr(effect, "item") else float(effect)
    p = float(pvalue.item()) if hasattr(pvalue, "item") else float(pvalue)
    return est, p